### ISSUE TITLE
Documentation for UiMenuItem is missing

### ISSUE THREAD

**Issue by mischnic** [parro-it/libui-napi#54]
And `npm r docs` fails

**Comment by parro-it** [comment]
I added tee menu item in #56. I had no problem running npm r docs. What kind of error do you get?

**Comment by mischnic** [comment]
```
$ npm run-script docs

> libui-napi@0.1.26 docs libui/libui-napi
> node tools/docs.js

{ JSDOC_ERROR: There are no input files to process.
    at Explain.verifyOutput (libui/libui-napi/node_modules/jsdoc-api/lib/jsdoc-command.js:113:19)
    at ChildProcess.handle.on.code (libui/libui-napi/node_modules/jsdoc-api/lib/explain.js:47:38)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:978:16)
    at Socket.stream.socket.on (internal/child_process.js:395:11)
    at Socket.emit (events.js:182:13)
    at Pipe._handle.close (net.js:616:12) name: 'JSDOC_ERROR' }
```

**Comment by mischnic** [comment]
Incredible: https://github.com/jsdoc3/jsdoc/issues/1328#issuecomment-282143743
> This normally happens because **one of the source file's parent directories starts with an underscore**. By default, JSDoc ignores source files in directories that begin with an underscore. To change this behavior, replace source.excludePattern with an empty string in your configuration file.

`~/Documents/_dev/_git/libui/libui-napi`
